# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET8 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_And_Run_Tests:

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies Project
      run: dotnet restore
      working-directory: TestNinjaNet8
    - name: Restore dependencies Tests
      run: dotnet restore
      working-directory: TestNinja.UnitTests
    - name: Build Project
      run: dotnet build --no-restore
      working-directory: TestNinjaNet8
    - name: Build Tests
      run: dotnet build --no-restore
      working-directory: TestNinja.UnitTests

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Wait for docker containers to setup
      run: sleep 30s
      shell: bash
      
    - name: Run Unit Test
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true
      env:
        BASE_URL: http://localhost:8095
  
    - name: Copy Unit Test Results
      run: mkdir TestResults; cp TestNinja.UnitTests/TestResults/test-results.trx TestResults/
      shell: bash
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx


    - name: Test1
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    #- name: Add Coverage PR Comment
      #uses: marocchino/sticky-pull-request-comment@v2
      #if: github.event_name == 'pull_request'
      #with:
        #recreate: true
        #path: code-coverage-results.md


    #- name: Publish Test Results
      #uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      #if: always()
      #with:
        #trx_files: TestResults/*.trx


