# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_And_Run_Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch unshallow
      run: git fetch --prune --tags --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies Project
      run: dotnet restore
      working-directory: TestNinjaNet8
    - name: Restore dependencies Tests
      run: dotnet restore
      working-directory: TestNinja.UnitTests
    - name: Build Project
      run: dotnet build --no-restore
      working-directory: TestNinjaNet8
    - name: Build Tests
      run: dotnet build --no-restore
      working-directory: TestNinja.UnitTests
    #- name: Create Test Results folder
      #run: mkdir TestResults
    - name: Run Unit Test      
      run: dotnet test --no-build --verbosity normal -- NUnit.TestOutputXml=TestResults
    - name: Copy Unit Test Results
      run: mkdir TestResults; cp TestNinja.UnitTests/bin/Debug/net8.0/TestResults/*.xml TestResults/
      shell: bash
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      #with:
        #name: Test Results
        #path: TestResults/*.trx
        #reporter: dotnet-trx


